# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string
     
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  aws_job:
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            example1
          parse-json-secrets: true

      - name: Input AWS secrets
        run: echo "Hello1 ${{ inputs.name }}! This is secrets - ${{ env.EXAMPLE1 }}"

      - name: Input AWS secrets2
        run: echo "Hello1 ${{ inputs.name }}! This is secrets2 - ${{ env.EXAMPLE1_MY_SECRETS }}"

      - name: Input AWS secrets3
        run: echo "Hello1 ${{ inputs.name }}! This is secrets3 - ${{ env.EXAMPLE1_SECR }}"

      - name: Input AWS secrets4
        run: echo ${{ env.EXAMPLE1_SECR }} | sed 's/./& /g'

      - name: Input AWS secrets4
        run: echo "SEC=${{ env.EXAMPLE1_MY_SECRETS }}" >> $GITHUB_ENV

      - name: Input AWS 44444
        run: echo "{{ $env.SEC }}"

      - name: Input AWS 55555
        run: echo "{{ $env.SEC }}" | sed 's/./& /g'    

      - name: Input AWS TTT
        run: echo "TTT=fffff" >> $GITHUB_ENV         

      - name: Input AWS TTT1
        run: echo $"{{ env.TTT }}"