# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  aws_job:
    runs-on: self-hosted
    steps:
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2 
        with:
          secret-ids: |
            SECRET_NAME, arn:aws:secretsmanager:eu-north-1:728490037630:secret:example1-h2fm95
      - name: AWS secrets
        run: echo "Hello1 ${{ inputs.name }}! This is secrets - ${{ env.SECRET_NAME }}"
